name: JCB Unit Tests

on: [push, pull_request]

jobs:
  jcb_unit_tests:
    runs-on: ubuntu-latest
    name: JCB Unit Tests
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Make sure python is up to date
        run: |
          pip install --upgrade pip

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install the code
        run: |
          cd $GITHUB_WORKSPACE
          pip install .[testing]

      - name: Run unit tests
        run: |
          cd $GITHUB_WORKSPACE
          pytest -v
